version: "3.8"
services:
  collector:
    build: .
    container_name: bybit_collector
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

